[tasks.profile]
description = "Run the emulator with a profiler"
run = [
  "cargo build --release",
  "samply record ./target/release/sad-boy ./roms/tetris.gb --debug",
]
tools."cargo:samply" = "0.13"

[tasks.test-profile]
description = "Run unit tests with profiling enabled"
run = """
#!/bin/sh
BIN=$(cargo test --no-run 2>&1 | rg 'target/[^)]*' -o)
samply record $BIN -- $@
"""

[tasks.dev]
description = "Run the emulator and restart on changes"
quiet = true
run = """
RUST_LOG="$usage_log_level" \
    watchexec --on-busy-update=restart --shell=none --wrap-process=none \
    --watch=Cargo.toml --watch=Cargo.lock --watch=src/ \
    -- cargo run -- $usage_rom --debug
"""
tools.watchexec = "2.3.3"
usage = """
arg "<rom>" help="ROM file"
flag "--log-level -l <level>" default="info" help="Set log level"
"""
